"""H1.2: `history` — compare sweeps over time (single offline HTML file).

Reads ``sweep-*.json`` from a target's ``.mycelium_benchmarks/`` directory and
renders one small-multiple SVG line chart per candidate (mean ±1 stddev over
time) plus a baseline trend table. Stdlib-only, zero network — same contract
as ``report_html``.
"""
from __future__ import annotations

import html
import json
from pathlib import Path
from typing import Any

_CSS = """
body{font-family:system-ui,sans-serif;max-width:900px;margin:2em auto;padding:0 1em;color:#222;}
.meta{color:#555;} table{border-collapse:collapse;margin:1em 0;} th,td{border:1px solid #ccc;padding:4px 10px;text-align:right;}
th:first-child,td:first-child{text-align:left;} .note{color:#666;font-size:13px;}
h2{margin-top:1.6em;border-bottom:1px solid #ddd;padding-bottom:4px;}
@media (prefers-color-scheme:dark){body{background:#121212;color:#e0e0e0}th{background:#2a2a2a}td,th{border-color:#555}h2{border-color:#444}.note,.meta{color:#aaa}}
@media print{body{max-width:100%;margin:0}svg{break-inside:avoid}}
"""


def load_sweeps(benchmarks_dir: Path) -> list[dict[str, Any]]:
    """Load sweep JSONs sorted by started_at; skips unreadable files."""
    sweeps = []
    for path in sorted(benchmarks_dir.glob("sweep-*.json")):
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except (ValueError, OSError):
            continue
        if isinstance(payload, dict) and isinstance(payload.get("summaries"), list):
            sweeps.append(payload)
    sweeps.sort(key=lambda s: s.get("started_at", 0))
    return sweeps


def _line_chart(points: list[tuple[float, float, float]], lower_is_better: bool) -> str:
    """points = (x_index, mean, stddev). Mean line + ±1 stddev band."""
    import math

    # C8: broken sweeps (nan/inf means) used to poison the polyline with
    # literal "nan" coordinates; skip them (the table-free chart only ever
    # claimed the finite points) and clamp wild stddevs to 0.
    points = [(x, m, s if math.isfinite(s) else 0.0)
              for x, m, s in points if math.isfinite(m)]
    if not points:
        return "<p>No finite means.</p>"
    w, h, pad = 640, 160, 30
    lo = min(m - s for _, m, s in points if math.isfinite(m))
    hi = max(m + s for _, m, s in points if math.isfinite(m))
    span = (hi - lo) or 1.0
    n = len(points)

    def x(i: int) -> float:
        return pad + (w - 2 * pad) * (i / max(1, n - 1))

    def y(v: float) -> float:
        return h - pad - (h - 2 * pad) * ((v - lo) / span)

    coords = [(x(i), y(m)) for i, (_, m, _) in enumerate(points)]
    line = " ".join(f"{a:.1f},{b:.1f}" for a, b in coords)
    band = " ".join(f"{x(i):.1f},{y(m - s):.1f}" for i, (_, m, s) in enumerate(points))
    band += " " + " ".join(f"{x(i):.1f},{y(m + s):.1f}" for i, (_, m, s) in reversed(list(enumerate(points))))
    color = "#2a7a2a" if lower_is_better else "#4a90d9"
    dots = "".join(f'<circle cx="{a:.1f}" cy="{b:.1f}" r="3" fill="{color}"/>' for a, b in coords)
    return (
        f'<svg width="{w}" height="{h}" role="img">'
        f'<polygon points="{band}" fill="{color}" opacity="0.15"/>'
        f'<polyline points="{line}" fill="none" stroke="{color}" stroke-width="2"/>'
        f"{dots}"
        f'<text x="{pad}" y="{h - 8}" font-size="11">sweep 1 → {n} (range {lo:.4g}–{hi:.4g})</text>'
        "</svg>"
    )


def history_html(sweeps: list[dict[str, Any]]) -> str:
    """Render loop-free history HTML from ``BenchmarkSweep.to_dict()`` payloads."""
    target = html.escape(str(sweeps[0].get("target", "?"))) if sweeps else "?"
    metric = html.escape(str(sweeps[0].get("metric", "?"))) if sweeps else "?"
    lower_is_better = bool(sweeps and sweeps[0].get("lower_is_better", True))
    names: list[str] = []
    for sweep in sweeps:
        for s in sweep.get("summaries", []):
            if s.get("candidate") not in names:
                names.append(s.get("candidate"))
    sections = []
    for name in names:
        points = []
        for i, sweep in enumerate(sweeps):
            match = next((s for s in sweep.get("summaries", []) if s.get("candidate") == name), None)
            if match is None:
                continue
            points.append((float(i), float(match.get("mean", float("nan"))),
                           float(match.get("stddev", 0.0) or 0.0)))
        sections.append(f"<h2>{html.escape(str(name))}</h2>\n{_line_chart(points, lower_is_better)}")
    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<title>Sweep history — {target}</title>
<style>{_CSS}</style></head>
<body>
<h1>Sweep history</h1>
<p class="meta">target: <code>{target}</code> · metric: <code>{metric}</code> · {len(sweeps)} sweeps
(band = ±1 stddev, NOT a confidence interval)</p>
{"".join(sections)}
<p class="note">Generated by mycelium-accel history (stdlib-only, offline).</p>
</body></html>
"""


def write_history(benchmarks_dir: Path, out: Path | None = None) -> tuple[Path, int]:
    sweeps = load_sweeps(benchmarks_dir)
    if len(sweeps) < 2:
        raise SystemExit(
            f"mycelium-accel: history needs ≥2 sweeps in {benchmarks_dir} "
            f"(found {len(sweeps)}); run accelerate at least twice"
        )
    dest = out or (benchmarks_dir / "history.html")
    dest.write_text(history_html(sweeps), encoding="utf-8")
    return dest, len(sweeps)
